// GAME ACTIONS
export const SCREEN_TRACKER_ACTIVE_OR_INACTIVE = 'SCREEN_TRACKER_ACTIVE_OR_INACTIVE';

export const SET_GAME_DATA = 'SET_GAME_DATA';
export const SINGLE_TYPE_TIMER_END = 'SINGLE_TYPE_TIMER_END';
export const MULTILEVEL_TYPE_TIMER_END = 'MULTILEVEL_TYPE_TIMER_END';
export const RESET_GAME_STATE = 'RESET_GAME_STATE';
export const SHOW_LEVELS_DIALOGUE = 'SHOW_LEVELS_DIALOGUE';
export const SHOW_TYPE_DIALOGUE = 'SHOW_TYPE_DIALOGUE';
export const SET_GAME_LEVEL = 'SET_GAME_LEVEL';
export const LEVELS_DIALOGUE_TIMER_END = 'LEVELS_DIALOGUE_TIMER_END';
export const PLAYER_ROUND_TIMER_END = 'PLAYER_ROUND_TIMER_END';
export const ROUND_TIMER_ALMOST_UP = 'ROUND_TIMER_ALMOST_UP';
export const PRE_PLAYER_TIMER_END = 'PRE_PLAYER_TIMER_END';

export const PLAYER_ROUND_OVER = 'PLAYER_ROUND_OVER';
export const SINGLE_GAME_OVER = 'SINGLE_GAME_OVER';
export const RESTART_LAST_MISSION = 'RESTART_LAST_MISSION';
