// GAME ACTIONS
export const SCREEN_TRACKER_ACTIVE_OR_INACTIVE = 'SCREEN_TRACKER_ACTIVE_OR_INACTIVE';

export const SET_GAME_DATA = 'SET_GAME_DATA';
export const SINGLE_TYPE_TIMER_END = 'SINGLE_TYPE_TIMER_END';
export const MULTILEVEL_TYPE_TIMER_END = 'MULTILEVEL_TYPE_TIMER_END';
export const RESET_GAME_STATE = 'RESET_GAME_STATE';
export const SHOW_LEVELS_DIALOGUE = 'SHOW_LEVELS_DIALOGUE';
export const SHOW_TYPE_DIALOGUE = 'SHOW_TYPE_DIALOGUE';
// export const SET_GAME_LEVEL = 'SET_GAME_LEVEL';
export const LEVELS_DIALOGUE_TIMER_END = 'LEVELS_DIALOGUE_TIMER_END';
export const PLAYER_ROUND_TIMER_END = 'PLAYER_ROUND_TIMER_END';
export const ROUND_TIMER_ALMOST_UP = 'ROUND_TIMER_ALMOST_UP';
export const PRE_PLAYER_TIMER_END = 'PRE_PLAYER_TIMER_END';

export const PLAYER_ROUND_OVER = 'PLAYER_ROUND_OVER';
export const SINGLE_GAME_OVER = 'SINGLE_GAME_OVER';
export const LEVEL_OVER = 'LEVEL_OVER';
export const MULTILEVEL_GAME_OVER = 'MULTILEVEL_GAME_OVER';
export const RESTART_LAST_MISSION = 'RESTART_LAST_MISSION';
export const RESTART_MULTILEVEL_MISSION = 'RESTART_MULTILEVEL_MISSION';
export const START_NEXT_LEVEL = 'START_NEXT_LEVEL';

// AUTH ACTIONS
export const USER_AVATAR_SELECTED = 'USER_AVATAR_SELECTED';

export const CHECK_USERNAME_AVAILABILITY_START = 'CHECK_USERNAME_AVAILABILITY_START';
export const CHECK_USERNAME_AVAILABILITY_SUCCESS = 'CHECK_USERNAME_AVAILABILITY_SUCCESS';
export const CHECK_USERNAME_AVAILABILITY_FAIL = 'CHECK_USERNAME_AVAILABILITY_FAIL';

export const REGISTER_USER_START = 'REGISTER_USER_START';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_FAIL = 'REGISTER_USER_FAIL';

export const RESET_REGISTER_PAGE = 'RESET_REGISTER_PAGE';

export const LOGIN_USER_START = 'LOGIN_USER_START';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAIL = 'LOGIN_USER_FAIL';

export const RESET_LOGIN_PAGE = 'RESET_LOGIN_PAGE';
