// GAME ACTIONS
export const SET_GAME_DATA = 'SET_GAME_DATA';
export const SINGLE_TYPE_TIMER_END = 'SINGLE_TYPE_TIMER_END';
export const MULTILEVEL_TYPE_TIMER_END = 'MULTILEVEL_TYPE_TIMER_END';
export const RESET_GAME_STATE = 'RESET_GAME_STATE';
export const SHOW_LEVELS_DIALOGUE = 'SHOW_LEVELS_DIALOGUE';
export const SHOW_TYPE_DIALOGUE = 'SHOW_TYPE_DIALOGUE';